// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Tf7Tdiv07RQquPv4e7auAHf1FrNYN6M',
    appId: '1:853215665727:web:c8506408e5e222f468e28a',
    messagingSenderId: '853215665727',
    projectId: 'flutterhelloworld-1bd58',
    authDomain: 'flutterhelloworld-1bd58.firebaseapp.com',
    storageBucket: 'flutterhelloworld-1bd58.appspot.com',
    measurementId: 'G-BEVN0KZLNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPspkGLAvNaSR7dCSqenv6Ce7yxNHinEQ',
    appId: '1:853215665727:android:a0945f68a694f81568e28a',
    messagingSenderId: '853215665727',
    projectId: 'flutterhelloworld-1bd58',
    storageBucket: 'flutterhelloworld-1bd58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWCM4RAkn9AqaTE3TursCxxRvCCfb_nWI',
    appId: '1:853215665727:ios:b66732f0b0264df168e28a',
    messagingSenderId: '853215665727',
    projectId: 'flutterhelloworld-1bd58',
    storageBucket: 'flutterhelloworld-1bd58.appspot.com',
    iosClientId: '853215665727-sgk64hli0kcmpj80bfb48dag1a0pgpas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHelloWorld',
  );
}
